#!/stage1/sh
export _PATH="$PATH"
export PATH="/stage1"

mkdir -p /dev/block
mknod -m 0644 /dev/block/bml7 b 137 7
mknod -m 0644 /dev/block/bml8 b 137 8
mknod -m 0644 /dev/block/bml9 b 137 9
mknod -m 0644 /dev/block/bml10 b 137 10
mknod -m 0644 /dev/block/bml11 b 137 11
mknod -m 0644 /dev/block/stl7 b 138 7
mknod -m 0644 /dev/block/stl8 b 138 8
mknod -m 0644 /dev/block/stl9 b 138 9
mknod -m 0644 /dev/block/stl10 b 138 10
mknod -m 0644 /dev/block/stl11 b 138 11

mknod -m 0644 /dev/block/mmcblk0 b 179 0
mknod -m 0644 /dev/block/mmcblk0p1 b 179 1

mkdir /cache
mkdir /proc
mkdir /sys

date >>/boot.txt
exec >>/boot.txt 2>&1
cd /
mount -t proc proc /proc
mount -t sysfs sysfs /sys

rm /init

dd bs=512 if=/dev/block/bml7 of=/stage1/boot.bin

eval $(grep -m 1 -A 1 BOOT_IMAGE_OFFSETS /stage1/boot.bin | tail -n 1)

load_offset=$boot_offset
load_len=$boot_len
 
REC_BOOT_ADDR="0x57fff800"
REC_BOOT_MAGIC="0x5EC0B007" # Must be in caps.

if test `devmem "$REC_BOOT_ADDR" 32` = "$REC_BOOT_MAGIC" || grep -q bootmode=2 /proc/cmdline ; then
	# recovery boot
	devmem "$REC_BOOT_ADDR" 32 0x0
	load_offset=$recovery_offset
	load_len=$recovery_len

	# disable lpm
	echo 0 > /sys/class/power_supply/battery/charging_mode_booting
fi

umount /cache
rm -rf /cache

dd bs=512 if=/stage1/boot.bin skip=$load_offset count=$load_len | zcat | cpio -i

if grep -q 1 /sys/class/power_supply/battery/charging_mode_booting ; then
	# low power mode
	cp lpm.rc init.rc
fi

umount /sys
umount /proc
date >> /boot.txt

rm -rf /stage1 
rm -rf /dev/*

export PATH="${_PATH}"

exec /init
